### ISSUE TITLE
Get metadata on mopidy-stream

### ISSUE THREAD

**Issue by gustavo-gomez** [schinken/docker-container#6]
Hi, I am using your container and it works very well. I am wondering how can I see artist name and track title for example, on iTunes. I created a M3U file to open it with iTunes but I just see "mopidy" on the stream information.

I also tried creating a radio station on TuneIn and I just see "Live".

Thanks.

**Comment by schinken** [comment]
That information is lost in the liquidsoap step. Basically it's the idea that information get lost. liquidsoap helps me to discard the EOS (End-Of-Stream) event, sent by mopidy. It's a known mopidy bug and if EOS emitted, all streaming clients get a disconnect after every track.

Liquidsoap prevents this, but other metainformation is also lost. If the bug in mopidy is fixed, I will update the container and then use icecast2 for streaming

**Comment by gustavo-gomez** [comment]
I see, thanks for your response!
