### ISSUE TITLE
having trouble streaming though 8800

### ISSUE THREAD

**Issue by danielbarter** [schinken/docker-container#7]
Hi there!

I am having trouble getting the stream to work properly.

When I point a browser at localhost:8800, the head of the response is liquidsoap source harbor and the body tells me that the page is not avaliable. Not so suprising. 

When I point mplayer at localhost:8800, i get the following error:

```
Playing http://localhost:8800.
Resolving localhost for AF_INET6...
Connecting to server localhost[::1]: 8800...

Server returned 404: Not found
STREAM_ASF, URL: http://localhost:8800
Resolving localhost for AF_INET6...
Connecting to server localhost[::1]: 8800...

Server returned 404:Not found
Failed to parse header.
Failed, exiting.
Resolving localhost for AF_INET6...
Connecting to server localhost[::1]: 8800...

Server returned 404: Not found
No stream found to handle url http://localhost:8800
```
any ideas?

**Comment by schinken** [comment]
The stream is running on http://<containerIp>:8800/mopidy

**Comment by danielbarter** [comment]
thanks! the issue is resolved
